// <auto-generated />
namespace FishDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addKey : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addKey));
        
        string IMigrationMetadata.Id
        {
            get { return "202201261931266_addKey"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
