// <auto-generated />
namespace FishDemo.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class dateFormating : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dateFormating));
        
        string IMigrationMetadata.Id
        {
            get { return "202201271331402_dateFormating"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
